# This file is machine-generated - editing it directly is not advised

[[Markets]]
uuid = "b44f5480-3750-11e9-03b7-d5e34f572a03"
version = "0.1.1"

[[Reexport]]
git-tree-sha1 = "6b9a637e33dfb9ceff7f01938408c344fa926ce3"
repo-rev = "master"
repo-url = "https://github.com/simonster/Reexport.jl.git"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0+"
